orbit-mvi/orbit-mvi

buildSrc/src/main/kotlin/DependencyManagement.kt

Releases aren't closing properly because of https://github.com/vanniktech/gradle-maven-publish-plugin/issues/193

Update to latest gradle maven publish plugin to fix close/release

---

.idea/artifacts/orbit_core_jvm.xml
.idea/artifacts/orbit_test_jvm.xml
.idea/artifacts/test_common_jvm.xml
.idea/codeStyles/Project.xml
.idea/jarRepositories.xml
build.gradle.kts
orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/internal/TestContainerDecorator.kt
orbit-test/src/commonMain/kotlin/org/orbitmvi/orbit/Test.kt
test-common/src/commonMain/kotlin/org/orbitmvi/orbit/test/Assertions.kt
test-common/src/commonMain/kotlin/org/orbitmvi/orbit/test/IgnoreIos.kt
test-common/src/iosMain/kotlin/org/orbitmvi/orbit/test/IgnoreIos.kt
test-common/src/jvmMain/kotlin/org/orbitmvi/orbit/test/Blocking.kt

When we changed the kotlin plugin type the explicit API mode failed to apply.

Fixed explicit API mode not working on multiplatform projects

---

orbit-core/README.md
orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/Container.kt
orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/internal/RealContainer.kt
orbit-core/src/commonTest/kotlin/org/orbitmvi/orbit/internal/ContainerExceptionHandlerTest.kt
samples/orbit-posts/src/main/kotlin/org/orbitmvi/orbit/sample/posts/app/features/postlist/ui/PostListItem.kt
samples/orbit-posts/src/main/kotlin/org/orbitmvi/orbit/sample/posts/app/features/postlist/viewmodel/PostListViewModel.kt

As discussed at Slack, 
it would be nice to have option to install "default" exception handler for the container, so any exception thrown doesn't affect parent scope (and orbit container). Note, by default (if handler is null) behaviour doesn't change.

Add container exception handler support

---

.github/workflows/android.yml
orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/Container.kt
orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/internal/LazyCreateContainerDecorator.kt
orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/internal/RealContainer.kt
orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/internal/StateFlowExtensions.kt
orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/internal/TestContainerDecorator.kt
orbit-core/src/commonTest/kotlin/org/orbitmvi/orbit/internal/ContainerExceptionHandlerTest.kt
orbit-core/src/commonTest/kotlin/org/orbitmvi/orbit/internal/ContainerThreadingTest.kt
orbit-core/src/commonTest/kotlin/org/orbitmvi/orbit/internal/StateTest.kt
orbit-viewmodel/src/main/kotlin/org/orbitmvi/orbit/viewmodel/SavedStateContainerDecorator.kt
orbit-viewmodel/src/main/kotlin/org/orbitmvi/orbit/viewmodel/StateFlowExtensions.kt
orbit-viewmodel/src/test/kotlin/org/orbitmvi/orbit/viewmodel/ViewModelExtensionsKtTest.kt

#36 Needs to be go in first
`StateFlow` is a more appropriate type for our use case for state emissions and allows us to get rid of `currentState` from the API as you can read the current state through `stateFlow.value`.

Replaced `Flow` with `StateFlow` for state emissions

---

orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/internal/RealContainer.kt
orbit-core/src/commonTest/kotlin/org/orbitmvi/orbit/internal/ContainerExceptionHandlerTest.kt

Intents that never finish (like collecting an infinite flow) would block the event loop due to an errant `supervisorScope` which waited for the launched intent to finish

Fix blocked event loop when exception handler is installed

---

orbit-core/src/commonTest/kotlin/org/orbitmvi/orbit/internal/ContainerExceptionHandlerTest.kt
orbit-test/src/commonMain/kotlin/org/orbitmvi/orbit/TestContainerHost.kt

The `exceptionHandler` is completely ignored in `test()` mode -> that means tests are effectively broken even code works nicely in production.

Fix Settings' `exceptionHandler` to be still counted in test() mode

---

orbit-test/src/commonMain/kotlin/org/orbitmvi/orbit/TestContainerHost.kt

Sometimes we have if-else branches without need to invoke `intent{}`, e.g.:
```
fun onLocationQuery(query: String) {        
if (query.length < MIN_QUERY_LENGTH_TO_PERFORM_SEARCH) {
return // no intent needed
}
performSuggestionsSearch(query) // intent{} inside, the func is reused later
}
```

Allow non-intent calls

---

orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/internal/RealContainer.kt
orbit-core/src/commonTest/kotlin/org/orbitmvi/orbit/internal/ContainerExceptionHandlerTest.kt

Currently `settings.exceptionHandler` breaks cancellation propagation
because it's supervisor job is not connected to the parent scope's one.

Fix cancellation propagation in case of ExceptionHandler

---

samples/orbit-posts/src/main/kotlin/org/orbitmvi/orbit/sample/posts/app/features/MainActivity.kt
samples/orbit-posts/src/main/kotlin/org/orbitmvi/orbit/sample/posts/app/features/postdetails/ui/PostDetailsFragment.kt
samples/orbit-posts/src/main/kotlin/org/orbitmvi/orbit/sample/posts/app/features/postlist/ui/PostListFragment.kt
samples/orbit-posts/src/main/kotlin/org/orbitmvi/orbit/sample/posts/app/features/postlist/ui/PostListItem.kt
samples/orbit-posts/src/main/kotlin/org/orbitmvi/orbit/sample/posts/app/features/postlist/viewmodel/PostListViewModel.kt
samples/orbit-posts/src/main/kotlin/org/orbitmvi/orbit/sample/posts/data/posts/network/PostNetworkDataSource.kt
samples/orbit-posts/src/main/kotlin/org/orbitmvi/orbit/sample/posts/data/posts/network/TypicodeService.kt
samples/orbit-posts/src/main/res/layout/main_activity.xml
samples/orbit-posts/src/main/res/layout/post_details_fragment.xml
samples/orbit-posts/src/main/res/layout/post_list_fragment.xml
samples/orbit-posts/src/test/kotlin/org/orbitmvi/orbit/sample/posts/data/posts/network/PostNetworkDataSourceTest.kt

Toolbar has moved inside the fragments so we can still use a coordinator layout but don't need to wrap the fragment in a NestedScrollView that was forcing every item of the RecyclerView to inflate causing performance issues.
Fixes #85

Remove NestedScrollView as recycler items were all inflating

---

website/docs/Android-ViewModel/overview.md

Updates the documentation to use the same ViewModel class name (`ExampleViewModel`) for consistency purposes.

Updates Android-ViewModel viewmodel name

---

website/docs/Android-ViewModel/overview.md

Replaces the use of deprecated stateViewModel with viewModel, According to Koin's docs:
> getStateViewModel will be merged to viewModel - no need anymore of state parameter

Updates Android-ViewModel to remove stateViewModel

---

orbit-core/orbit-core_build.gradle.kts
orbit-test/orbit-test_build.gradle.kts
test-common/test-common_build.gradle.kts

Based on #97, just fixed detekt
See https://kotlinlang.org/docs/mpp-share-on-platforms.html#target-shortcuts-and-arm64-apple-silicon-simulators for details.
This is needed so projects using Orbit can run on the iOS Simulators on Apple Silicon (M1) Macs.

Support Apple Silicon simulators

---

orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/internal/AlwaysSubscribedCounter.kt
orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/internal/RealContainer.kt
orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/internal/TestContainerDecorator.kt
orbit-test/src/commonMain/kotlin/org/orbitmvi/orbit/TestFlowObserver.kt
orbit-test/src/commonTest/kotlin/org/orbitmvi/orbit/RepeatOnSubscriptionTest.kt

Fixes #102.
`repeatOnSubscription` collects a flow of `subscribed/unsubscribed` events infinitely. This is a problem in suspending tests, as we want the block to complete if it doesn't contain any infinite flow collection.
The solution is to replace the `subscribed` flow with a cold finite flow of `Subscription.Subscribed` - This will mean that in tests the block always executes.

Fix repeatOnSubscription in tests

---

orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/CoroutineScopeExtensions.kt
orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/internal/TestContainerDecorator.kt
orbit-test/src/commonMain/kotlin/org/orbitmvi/orbit/Test.kt
orbit-test/src/commonMain/kotlin/org/orbitmvi/orbit/TestContainerHost.kt
orbit-test/src/commonTest/kotlin/org/orbitmvi/orbit/GeneralTest.kt
website/docs/Test/overview.md

Fixes #103 . 
Passing no initial state to `test()` method is now allowed. In that case, the real initial state is used.

Allow omitting initial state in tests

---

README.md

In the Jetpack Compose example code in the README, `navController` is used for the `handleSideEffect` function argument, but the `navController` argument does not exist in the `handleSideEffect` function implementation. I think this should be fixed as it can be confusing.
Now:
```kotlin
@Composable
fun CalculatorScreen(viewModel: CalculatorViewModel) {
val state = viewModel.collectAsState().value
viewModel.collectSideEffect { handleSideEffect(navController, it) }
// render UI using data from 'state'
...
}
private fun handleSideEffect(sideEffect: CalculatorSideEffect) {
when (sideEffect) {
is CalculatorSideEffect.Toast -> toast(sideEffect.text)
}
}
```
Should edited:
```kotlin
@Composable
fun CalculatorScreen(viewModel: CalculatorViewModel) {
val state = viewModel.collectAsState().value …
```

Fix example code error

---

orbit-test/src/commonMain/kotlin/org/orbitmvi/orbit/test/OrbitTestContext.kt
orbit-test/src/commonMain/kotlin/org/orbitmvi/orbit/test/RealOrbitTestContext.kt
orbit-test/src/commonTest/kotlin/org/orbitmvi/orbit/test/ItemsTest.kt

This can be useful, for example, for expecting that some condition resulted in a side effect not being called

Add expectNoItems to OrbitTestContext

---

orbit-compose/src/main/kotlin/org/orbitmvi/orbit/compose/ContainerHostExtensions.kt

Fixes an issue in cases where side effect collection lambdas capture some outside parameters.
Since we use a `LaunchedEffect` that lambda would never change, even if the provided one did - resulting in always using the original captured parameters.

Fix compose extensions capturing lambda parameters forever

---

gradle/libs.versions.toml

Currently Orbit pins consumers back to Turbine 0.13.0, since Turbine 1.0.0 contains binary incompatible changes from 0.13.0.

Update Turbine to 1.0.0

---

gradle/libs.versions.toml
orbit-compose/orbit-compose_build.gradle.kts
orbit-compose/src/main/kotlin/org/orbitmvi/orbit/compose/ContainerHostExtensions.kt
orbit-compose/src/test/kotlin/org/orbitmvi/orbit/compose/ContainerHostExtensionsKtTest.kt
orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/Container.kt
orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/ContainerDecorator.kt
orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/RealSettings.kt
orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/internal/InterceptingContainerDecorator.kt
orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/internal/LazyCreateContainerDecorator.kt
orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/internal/RealContainer.kt
orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/internal/TestContainerDecorator.kt
orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/internal/repeatonsubscription/DelayingSubscribedCounter.kt
orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/internal/repeatonsubscription/SubscribedCounter.kt
orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/syntax/simple/SimpleSyntaxExtensions.kt
orbit-core/src/commonTest/kotlin/org/orbitmvi/orbit/internal/RefCountSideEffectTest.kt
orbit-core/src/commonTest/kotlin/org/orbitmvi/orbit/internal/RefCountStateTest.kt
orbit-core/src/commonTest/kotlin/org/orbitmvi/orbit/internal/repeatonsubscription/RepeatOnSubscriptionTest.kt
orbit-core/src/commonTest/kotlin/org/orbitmvi/orbit/internal/repeatonsubscription/TestSubscribedCounter.kt
orbit-viewmodel/src/main/kotlin/org/orbitmvi/orbit/viewmodel/ContainerHostExtensions.kt

`repeatOnSubscription` is an API designed to repeat a block of code whenever the total number of subscribers to a Container's StateFlow + Side effect flow goes from 0 -> 1, and conversely - cancel this block's coroutine when it goes down to 0.
We have not taken into account that one could be subscribing to the Container's state updates within its `ContainerHost`. This causes a subscription that lasts until the scope is cancelled, so the `repeatOnSubscription` block is never cancelled , and thus, never repeated - even if all external subscribers (e.g. the UI) drop away.
To remediate this, we:
1. `stateFlow` and `sideEffectFlow` had their refcount operators removed. From now on, subscribing to these will not be taken into account for the subscriber count used in `repeatOnSubscription`
2. …

Fix repeatOnSubscription to take into account external subscribers only

---

orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/RealSettings.kt
orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/internal/RealContainer.kt
orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/syntax/simple/SimpleSyntaxExtensions.kt
orbit-core/src/commonTest/kotlin/org/orbitmvi/orbit/syntax/simple/SimpleDslThreadingTest.kt
orbit-test/src/commonMain/kotlin/org/orbitmvi/orbit/SettingsBuilder.kt
orbit-test/src/commonMain/kotlin/org/orbitmvi/orbit/test/Test.kt

Due to our use of the `Unconfined` dispatcher for launching intent coroutines off the Orbit event loop, we ran into cases where the continuation of some intents after re-subscription would resume on the `main` dispatcher. This is entirely unintended and has the potential to cause bugs like frame drops etc.
I found a way to keep the existing behaviour, but drop the unconfined dispatcher. Continuations should now resume in the dispatcher taken from the coroutine context.

Remove unconfined dispatcher from intent launch

---

orbit-viewmodel/src/main/kotlin/org/orbitmvi/orbit/viewmodel/SavedStateContainerDecorator.kt
orbit-viewmodel/src/test/kotlin/org/orbitmvi/orbit/viewmodel/ViewModelExtensionsKtTest.kt

In versions 7.0.0 to 7.1.1
When I use SavedStateHandle in ViewModel and collect state using Compose collectAsState, the state is not saved to SavedStateHandle.

Fix state is not saved to SavedStateHandle

---

build.gradle.kts
gradle/libs.versions.toml
orbit-core/orbit-core_build.gradle.kts
orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/internal/LazyCreateContainerDecorator.kt
orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/internal/RealContainer.kt
orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/internal/TestContainerDecorator.kt
orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/internal/repeatonsubscription/DelayingSubscribedCounter.kt
orbit-core/src/commonTest/kotlin/org/orbitmvi/orbit/syntax/simple/SimpleDslIdlingTest.kt
orbit-core/src/commonTest/kotlin/org/orbitmvi/orbit/syntax/simple/SimpleDslRepeatOnSubscriptionTest.kt
orbit-test/orbit-test_build.gradle.kts
orbit-test/src/commonTest/kotlin/org/orbitmvi/orbit/test/InitTest.kt
test-common/src/commonMain/kotlin/org/orbitmvi/orbit/test/ScopedBlockingWorkSimulator.kt
test-common/test-common_build.gradle.kts

Kotlin 2.1.20 introduces common atomic types to the standard library - see https://kotlinlang.org/docs/whatsnew2120.html#common-atomic-types. By switching to this we are able to remove the dependency on AtomicFu which often causes us dependency issues.
Fixes #248

Replace AtomicFu with Kotlin standard library implementation

---

.github/workflows/build-and-release.yml
gradle/libs.versions.toml
gradle/scripts/jacoco-android.gradle.kts
gradle/scripts/jacoco.gradle.kts

Multiplatform code doesn't automatically add a `jacocoTestReport` task so we have to manually add one and tell it about our source files.
Hopefully fixing #285

Enable jacoco coverage for multiplatform
